import { StartupProfile } from "./types";

export const MOCK_STARTUPS: StartupProfile[] = [
  {
    id: "startup-01",
    submittedAt: "2025-11-01T08:00:00Z",
    onboarding: {
      companyName: "FinFlow AI",
      tagline: "AI-native CFO for SME finance teams",
      founded: "2024",
      website: "https://finflow.ai",
      sector: "Fintech",
      geography: "India",
      founderName: "Arjun Mehta",
      founderRole: "CEO & Co-Founder",
      founderBio: "Ex-Goldman Sachs, IIT Bombay, built FinFlow to solve FP&A for 10M Indian SMEs",
      teamSize: 12,
      keyMembers: "Priya Kar (CTO, ex-Razorpay), Rohit Sen (CFO, CA + IIM)",
      advisors: "Nithin Kamath (Zerodha), Shailendra Singh (Sequoia)",
      businessModel: "B2B SaaS",
      revenueModel: "Subscription (per seat) + transaction fee on AP automation",
      pricingStrategy: "₹5,000/seat/month, enterprise custom pricing",
      targetCustomer: "Indian SMEs with ₹10Cr–₹500Cr revenue and 5–50 finance team members",
      problem: "SME CFOs spend 60% of time on manual reconciliation; FP&A tools are too complex or too expensive",
      solution: "AI agent that automates reconciliation, generates board-ready reports, and forecasts cash flow in real time",
      uniqueValueProp: "First AI CFO purpose-built for Indian SME accounting workflows (Tally, Busy, SAP B1)",
      competitiveAdvantage: "Proprietary Indian SME financial data model + deep integrations with Tally & GST portals",
      mrr: "$42,000",
      arr: "$504,000",
      customers: "87 paying customers",
      growthRate: "22% MoM",
      keyMetrics: "NPS 68, Churn <1.5%, CAC $320, LTV $8,400",
      partnerships: "ICICI Bank distribution partnership, Tally Solutions MoU",
      fundingStage: "Series A",
      askAmount: "$5M",
      useOfFunds: "40% product (AI model finetuning), 35% GTM (inside sales team), 25% infra",
      prevFunding: "$1.2M Pre-Seed (Blume Ventures + angels)",
      runway: "18 months",
      valuation: "$28M pre-money",
    },
  },
  {
    id: "startup-02",
    submittedAt: "2025-11-03T11:30:00Z",
    onboarding: {
      companyName: "NovaMed",
      tagline: "AI diagnostics at the point of care",
      founded: "2023",
      website: "https://novamed.health",
      sector: "HealthTech",
      geography: "India",
      founderName: "Dr. Kavya Reddy",
      founderRole: "Founder & CTO",
      founderBio: "AIIMS radiologist turned AI researcher; published 12 papers on ML in medical imaging",
      teamSize: 8,
      keyMembers: "Sunil Pai (CEO, ex-PharmEasy), Dr. Rajan Kumar (CMO)",
      advisors: "AIIMS Delhi partnership, Dr. Prathap Reddy (Apollo)",
      businessModel: "B2B SaaS",
      revenueModel: "SaaS subscription per clinic/hospital + per-scan API pricing",
      pricingStrategy: "$200/month per point-of-care device, $0.80 per scan API call",
      targetCustomer: "Tier 2/3 Indian hospitals, diagnostic chains, primary care clinics",
      problem: "70% of India lacks access to radiologists; misdiagnosis rates in T2/T3 cities are 40%+ for chest X-rays",
      solution: "Edge-deployed AI model reads chest X-rays, ECGs, and retinal scans with 95%+ accuracy in <3 seconds",
      uniqueValueProp: "Works offline on low-end hardware; trained on 2M+ Indian patient images",
      competitiveAdvantage: "CDSCO approved, offline-first, India-specific disease patterns (TB, dengue)",
      mrr: "$15,000",
      arr: "$180,000",
      customers: "34 clinics in 8 cities",
      growthRate: "18% MoM",
      keyMetrics: "Accuracy 96.2% (chest X-ray), 0 critical misses in 6 months, CDSCO Class B approval",
      partnerships: "Apollo Clinics pilot (50 centers), AIIMS Delhi research MoU",
      fundingStage: "Seed",
      askAmount: "$2.5M",
      useOfFunds: "50% clinical validation & regulatory, 30% product, 20% BD",
      prevFunding: "$400K from angels + BIRAC grant",
      runway: "14 months",
      valuation: "$12M pre-money",
    },
  },
  {
    id: "startup-03",
    submittedAt: "2025-11-05T09:15:00Z",
    onboarding: {
      companyName: "GridZero",
      tagline: "Zero-carbon energy management for commercial buildings",
      founded: "2023",
      website: "https://gridzero.energy",
      sector: "CleanTech",
      geography: "India",
      founderName: "Siddharth Nair",
      founderRole: "CEO",
      founderBio: "Ex-Tata Power, IIT Madras EE, 8 years in smart grid and energy storage",
      teamSize: 14,
      keyMembers: "Ananya Sharma (CTO, ex-ABB), Rajiv Kapoor (COO, ex-Schneider Electric)",
      advisors: "Former CMD of SECI, Ex-CTO of Greenko",
      businessModel: "B2B SaaS",
      revenueModel: "Monthly SaaS fee + energy savings share (10% of savings delivered)",
      pricingStrategy: "₹50K–₹2L/month based on building size + performance-linked incentive",
      targetCustomer: "Commercial buildings >50,000 sqft: IT parks, hotels, hospitals, malls",
      problem: "Commercial buildings account for 34% of India's electricity spend; 30–40% wasted on HVAC/lighting inefficiency",
      solution: "AI/IoT platform that autonomously optimizes energy consumption, predicts demand, and integrates renewable sources",
      uniqueValueProp: "Average 28% energy cost reduction within 90 days, zero upfront hardware cost for large customers",
      competitiveAdvantage: "Proprietary load-forecasting model trained on 500+ Indian buildings + hardware-agnostic IoT layer",
      mrr: "$58,000",
      arr: "$696,000",
      customers: "23 buildings (12M sqft managed)",
      growthRate: "15% MoM",
      keyMetrics: "₹8.2Cr energy savings delivered, 94% customer retention, NPS 71",
      partnerships: "Tata Realty (5 IT parks), DLF pilot",
      fundingStage: "Series A",
      askAmount: "$6M",
      useOfFunds: "45% hardware procurement, 35% sales, 20% R&D",
      prevFunding: "$1.5M Seed (Matrix Partners + SIDBI)",
      runway: "20 months",
      valuation: "$32M pre-money",
    },
  },
  {
    id: "startup-04",
    submittedAt: "2025-11-07T14:00:00Z",
    onboarding: {
      companyName: "LearnLift",
      tagline: "Upskilling India's workforce one micro-course at a time",
      founded: "2024",
      website: "https://learnlift.in",
      sector: "EdTech",
      geography: "India",
      founderName: "Meera Joshi",
      founderRole: "Founder & CEO",
      founderBio: "Ex-Byju's product head, IIM Ahmedabad, passionate about blue-collar workforce education",
      teamSize: 9,
      keyMembers: "Ravi Kumar (CTO, ex-Unacademy), Shruti Patel (CPO)",
      advisors: "Ronnie Screwvala (Upgrad), ex-NSDC Director",
      businessModel: "Marketplace",
      revenueModel: "B2B enterprise contracts + B2C subscription; revenue share with content creators",
      pricingStrategy: "B2B: ₹1,200/employee/year. B2C: ₹499/month",
      targetCustomer: "Manufacturing, logistics, and retail companies upskilling frontline workers",
      problem: "India's 500M blue-collar workforce lacks access to affordable, relevant, vernacular job-skills training",
      solution: "Mobile-first platform delivering 15-min micro-courses in 12 Indian languages with AI-personalized learning paths",
      uniqueValueProp: "Offline-capable, vernacular-first, tracks ROI with 'Skill Completion Certificates' linked to wage growth",
      competitiveAdvantage: "Proprietary vernacular content library (3,200+ modules), employer-paid model with measurable ROI",
      mrr: "$25,000",
      arr: "$300,000",
      customers: "18 enterprise clients (45,000 learners)",
      growthRate: "20% MoM",
      keyMetrics: "Course completion 74%, Certification rate 61%, NPS 63, Learner income +18% post-cert",
      partnerships: "Mahindra Logistics, Delhivery, Reliance Retail pilots",
      fundingStage: "Seed",
      askAmount: "$3M",
      useOfFunds: "40% content & tech, 35% sales, 25% ops",
      prevFunding: "$600K from angels",
      runway: "16 months",
      valuation: "$14M pre-money",
    },
  },
  {
    id: "startup-05",
    submittedAt: "2025-11-09T10:45:00Z",
    onboarding: {
      companyName: "SecureStack",
      tagline: "AI-powered cloud security for engineering teams",
      founded: "2024",
      website: "https://securestack.io",
      sector: "Cybersecurity",
      geography: "India",
      founderName: "Kunal Verma",
      founderRole: "CEO & Co-Founder",
      founderBio: "Ex-Palo Alto Networks, BITS Pilani CS, shipped 3 enterprise security products",
      teamSize: 11,
      keyMembers: "Tanya Singh (CTO, ex-Cloudflare), Amit Jha (Head of Sales, ex-Darktrace)",
      advisors: "Ex-CISO of Infosys, NASSCOM Cybersecurity Council member",
      businessModel: "B2B SaaS",
      revenueModel: "Annual SaaS + professional services for enterprise setup",
      pricingStrategy: "$800/developer/year; enterprise from $50K/year",
      targetCustomer: "Engineering-led startups and mid-market companies (50–500 developers) using AWS/GCP",
      problem: "85% of cloud breaches are due to misconfiguration; security is bolted on after dev, creating expensive remediation cycles",
      solution: "Developer-native security co-pilot that scans IaC, detects misconfigs in real time, and auto-remediates in CI/CD pipelines",
      uniqueValueProp: "Integrates in <30 min, zero false positives using AI risk scoring, reduces MTTR from days to minutes",
      competitiveAdvantage: "Proprietary Indian cloud security dataset; first mover in dev-sec-ops for Indian cloud-native startups",
      mrr: "$31,000",
      arr: "$372,000",
      customers: "41 paying teams",
      growthRate: "19% MoM",
      keyMetrics: "1.2M security events processed/day, CAC $1,800, LTV $26,000, churn 0.8%",
      partnerships: "AWS Partner Network (Select Tier), GitHub Marketplace listing",
      fundingStage: "Series A",
      askAmount: "$4M",
      useOfFunds: "50% GTM (US expansion), 30% product, 20% compliance & certifications",
      prevFunding: "$900K Pre-Seed (Blume + angels)",
      runway: "17 months",
      valuation: "$22M pre-money",
    },
  },
];
