import { VCFirm } from "./types";

export const MOCK_VCS: VCFirm[] = [
  {
    id: "vc-01",
    name: "Sequoia Capital India",
    logo: "S",
    tagline: "Helping the daring build legendary companies",
    description: "One of India's most active venture firms backing founders at every stage from Seed to Series B and beyond.",
    sectors: ["Fintech", "SaaS", "AI/ML", "E-commerce"],
    stages: ["Seed", "Series A", "Series B"],
    ticketMin: 1,
    ticketMax: 20,
    geographies: ["India", "Southeast Asia"],
    businessModels: ["B2B SaaS", "Marketplace", "B2C"],
    portfolioCount: 180,
    aum: "$2.8B",
    website: "https://sequoiacap.com",
    partners: ["Shailendra Singh", "Mohit Bhatnagar"],
  },
  {
    id: "vc-02",
    name: "Accel India",
    logo: "A",
    tagline: "The early stage VC for ambitious founders",
    description: "Accel has backed some of India's biggest success stories. Focus on early-stage B2B and consumer tech.",
    sectors: ["SaaS", "Fintech", "HealthTech", "EdTech"],
    stages: ["Seed", "Series A"],
    ticketMin: 0.5,
    ticketMax: 10,
    geographies: ["India", "Southeast Asia", "USA"],
    businessModels: ["B2B SaaS", "B2C", "Enterprise"],
    portfolioCount: 120,
    aum: "$1.5B",
    website: "https://accel.com",
    partners: ["Prashanth Prakash", "Prayank Swaroop"],
  },
  {
    id: "vc-03",
    name: "Elevation Capital",
    logo: "E",
    tagline: "Partnering with exceptional founders from Day 1",
    description: "Formerly SAIF Partners, Elevation Capital focuses on early-stage investments in consumer internet and enterprise software.",
    sectors: ["Fintech", "E-commerce", "SaaS", "AI/ML"],
    stages: ["Seed", "Series A", "Series B"],
    ticketMin: 1,
    ticketMax: 15,
    geographies: ["India"],
    businessModels: ["B2C", "B2B SaaS", "Marketplace", "D2C"],
    portfolioCount: 150,
    aum: "$2.0B",
    website: "https://elevationcapital.com",
    partners: ["Mayank Khanduja", "Mridul Arora"],
  },
  {
    id: "vc-04",
    name: "Blume Ventures",
    logo: "B",
    tagline: "First-check, last-mile investing",
    description: "India's leading pre-Series A fund with deep expertise in DeepTech, SaaS, and Climate.",
    sectors: ["DeepTech", "SaaS", "CleanTech", "AI/ML"],
    stages: ["Pre-Seed", "Seed"],
    ticketMin: 0.1,
    ticketMax: 3,
    geographies: ["India", "Southeast Asia"],
    businessModels: ["B2B SaaS", "API/Platform", "Hardware"],
    portfolioCount: 90,
    aum: "$450M",
    website: "https://blume.vc",
    partners: ["Sanjay Nath", "Karthik Reddy"],
  },
  {
    id: "vc-05",
    name: "Lightspeed India",
    logo: "L",
    tagline: "Fueling the next generation of innovators",
    description: "Global venture firm with a strong India franchise, investing across consumer, enterprise and frontier tech.",
    sectors: ["Fintech", "SaaS", "AI/ML", "Web3", "HealthTech"],
    stages: ["Series A", "Series B", "Series C+"],
    ticketMin: 5,
    ticketMax: 50,
    geographies: ["India", "USA", "Southeast Asia", "Global"],
    businessModels: ["B2B SaaS", "B2C", "Enterprise", "Marketplace"],
    portfolioCount: 200,
    aum: "$7.0B",
    website: "https://lsvp.com",
    partners: ["Bejul Somaia", "Hemant Mohapatra"],
  },
  {
    id: "vc-06",
    name: "Chiratae Ventures",
    logo: "C",
    tagline: "Building tomorrow's category leaders",
    description: "India-focused early-stage VC investing in technology companies solving real-world problems through innovation.",
    sectors: ["HealthTech", "EdTech", "SaaS", "Fintech"],
    stages: ["Seed", "Series A"],
    ticketMin: 0.5,
    ticketMax: 8,
    geographies: ["India"],
    businessModels: ["B2C", "B2B SaaS", "D2C", "Marketplace"],
    portfolioCount: 75,
    aum: "$800M",
    website: "https://chiratae.com",
    partners: ["Sudhir Sethi", "Venkat Vallabhaneni"],
  },
  {
    id: "vc-07",
    name: "Peak XV Partners",
    logo: "P",
    tagline: "Scaling bold ideas across Southeast Asia and India",
    description: "The Southeast Asia and India arm of Sequoia, one of the world's largest and most active venture firms.",
    sectors: ["Fintech", "SaaS", "AI/ML", "Web3", "Cybersecurity"],
    stages: ["Series A", "Series B", "Series C+"],
    ticketMin: 5,
    ticketMax: 100,
    geographies: ["India", "Southeast Asia", "Global"],
    businessModels: ["B2B SaaS", "Enterprise", "API/Platform"],
    portfolioCount: 250,
    aum: "$9B",
    website: "https://peakxv.com",
    partners: ["GV Ravishankar", "Rajan Anandan"],
  },
  {
    id: "vc-08",
    name: "Matrix Partners India",
    logo: "M",
    tagline: "Long-term partnerships for category-defining companies",
    description: "Matrix focuses on early-stage investments in SaaS, consumer brands, and fintech across India and Southeast Asia.",
    sectors: ["SaaS", "Fintech", "E-commerce", "CleanTech"],
    stages: ["Pre-Seed", "Seed", "Series A"],
    ticketMin: 0.5,
    ticketMax: 10,
    geographies: ["India", "Southeast Asia"],
    businessModels: ["B2B SaaS", "D2C", "B2C", "Marketplace"],
    portfolioCount: 100,
    aum: "$1.2B",
    website: "https://matrixpartners.in",
    partners: ["Avnish Bajaj", "Vikram Vaidyanathan"],
  },
];
